routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


    // Route::get('/', function () {
    // return view('testindex');});
    // Route::get('/', 'App\Http\Controllers\dataperusahaanController@index');


     Route::get('/', function () {
        return view('beranda');
    });

    Route::get('peminjamanview', function () {
        return view('beranda-admin-inventaris');
    });
    Route::get('riwayatviewadmin', function () {
        return view('beranda-admin-riwayat');
    });
    
    Route::get('peminjamanuser', function () {
        return view('beranda-user-inventaris');
    });

    Route::get('riwayatviewuser', function () {
        return view('beranda-user-riwayat');
    });

//route tabel data perusahaan
    Route::resource('dataperusahaan', '\App\Http\Controllers\dataperusahaanController');

//route tabel data invetaris barang
    Route::resource('databarang', '\App\Http\Controllers\databarangController');

//route tabel data Peminjaman
    Route::resource('peminjaman', '\App\Http\Controllers\peminjamanController');

//route tabel data Peminjaman admin
Route::resource('peminjamanAdmin', '\App\Http\Controllers\peminjamanAdminController');

 //route login dan daftar   
    Route::get('/login', function () {
        return view('login');
    })->name('login');
    
    Route::get('/daftar', function () {
        return view('daftar');
    })->name('daftar');
    
    Route::get('/email-success', function () {
        return view('email-success');
    })->name('email-success');
    
    Route::post('/daftar', [RegisterController::class, 'store'])->name('daftar');
    
    Route::post('/postlogin', [LoginController::class, 'postlogin'])->name('postlogin');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logoout');
    
    Route::get('/beranda', [BerandaController::class, 'index']);
    
    Route::group(['middleware' => ['auth', 'cekrole:admin']], function() {
        Route::get('/beranda-admin', [BerandaController::class, 'berandaadmin'])->name('beranda-admin');
    });
    
    Route::group(['middleware' => ['auth', 'cekrole:user']], function() {
        Route::get('/beranda-user', [BerandaController::class, 'berandauser'])->name('beranda-user');
    });
    
    Route::get('/forget-password', [ForgotPasswordController::class, 'getEmail']);
    Route::post('/forget-password', [ForgotPasswordController::class, 'postEmail']);
    
    Route::get('/reset-password/{token}', [ResetPasswordController::class, 'getPassword']);
    Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword']);  

resources/views/beranda-user.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>pkl</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="#" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                <img src="img/tvri.png" alt="logo" class="bi me-2" width="60" height="35" role="img" aria-label="Bootstrap">
            </a>
        
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 link-secondary">Beranda</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Layanan</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Karir</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Kontak</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Tentang Kami</a></li>
                <li><a href="/peminjamanuser" class="nav-link px-2 link-dark">Peminjaman barang</a></li>
            </ul>
        
            <div class="col-md-3 text-end">
                <div class="dropdown">
                    <a href="/logout">
                        <button class="btn btn-primary" type="button">
                            Logout
                        </button>
                    </a>
                </div>
            </div>
        </header>
    </div>
    
    <div class="b-example-divider"></div>
        
    <div class="container">
        <div class="p-5 mb-4 rounded-3 img-box">
            <div class="container-fluid py-5">
                <div class="row">
                    <div class="col-md-6">
                        <h1>Data Kerjasama Perusahaan</h1>
                    </div>
                  
                </div>
            </div>
        </div>
    </div> 
    
    <div class="container">
        <table id="tabelpt" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Perusahaan</th>
                    <th>Email Perusahaan</th>
                    <th>Keterangan</th>
                </tr>
            </thead>
           
        </table>
    </div>
    <footer id="footer" class="section-bg">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="footer-info">
                                    <h3>Visi</h3>
                                    <p>Terwuiudnya LPP TVRI yang mandiri dan Profesional guna menguatkan persatuan dan kesatuan bangsa dalam mendukung Visi dan Misi Presiden dan Wakil Presiden Yaitu lndonesia Maju yang Berdaulat, Mandiri, dan Berkepribadian Berlandaskan Gotong-royong .</p>
                                </div>
                                <div class="footer-newsletter">
                                    <h3>Misi</h3>
                                    <p>1. Memberikan dukungan teknis penyiaran publik dalam pengambilan kebijakan penyelangaraan pemerintahan / negara
                                        <br>
                                        2. Meningkatkan kualitas sumber daya manusia, sarana, dan prasarana LPP TVRI
                                        <br>
                                        3. Menyelenggarakan pelayanan yang efektif dan efisien di bidang pengelolaan sumber-sumber, pengawasan, administrasi umum, informasi dan hubungan kelembagaan</p>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="footer-links">
                                    <h4>Links</h4>
                                    <ul>
                                        <li><a href="#data_perusahaan">Data Perushaan</a></li>
                                        <li><a href="#data_inventaris_barang">Data Inventaris Barang</a></li>
                                        <li><a href="#">Basmi Hoax</a></li>
                                        <li><a href="#">Tentang TVRI</a></li>
                                    </ul>
                                </div>
                                <div class="footer-links">
                                    <h4>Hubungi Kami</h4>
                                    <p>
                                    Jl. Mayjen Sungkono No.124, Pakis, Kec. Sawahan, Kota SBY, Jawa Timur 60189 <br>
                                    <strong>Phone:</strong> (031) 5678515<br>
                                    <strong>Email:</strong> sekretariattvrijatim@gmail.com<br>
                                    </p>
                                </div>
                                <div class="social-links">
                                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15830.265211304128!2d112.69690803955078!3d-7.290083499999991!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd7fc734b7f3bd1%3A0xb549bdffa17f9ac3!2sTVRI%20Stasiun%20Jawa%20Timur!5e0!3m2!1sid!2sid!4v1661325501948!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>    
                        </div>    
                    </div>
                </div>
            </div>

           
        </div>
    </footer>







    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );    
    </script>
    <script>
        $('#example').dataTable( {
            "columnDefs": [
                { "width": "14%", "targets": 0 }
            ]
        } );
    </script>

<!-- SCRIPT AJAX -->

   


<script type="text/javascript">

    $(document).ready(function () {
              $.ajaxSetup({
                  headers: {
                      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  }
              });
          });
  
  
  
      $(document).ready(function() {
  
         var table = $('#tabelpt').DataTable({
              "pageLength": 50,
             processing : true,
             serverSide : true,
             ajax: {
  
              url: "{{route('dataperusahaan.index')}}",
              type: 'GET',
              
               },
               columns: [

                       {
                         data: 'DT_RowIndex',
                         name: 'DT_RowIndex'
                       },
                      
                      {
                          data:'nama_perusahaan',
                          name:'nama_perusahaan'
                      },
                      
                      {
                          data:'email',
                          name:'email'
                      },
                      {
                          data:'keterangan',
                          name:'keterangan'
                      },
  
                       
                    
                  ],
  
                  order:[
                  [0,'desc']
                  ]
  
  
              });
  //function auto reload table
              setInterval( function () {
      table.ajax.reload();
  }, 3000 );
      });
  
  
  
  
  
  
  </script>











</body>


</html>

resources/views/beranda.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PKL</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="#" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                <img src="img/tvri.png" alt="logo" class="bi me-2" width="60" height="35" role="img" aria-label="Bootstrap">
            </a>
        
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 link-secondary">Beranda</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Layanan</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Karir</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Kontak</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Tentang Kami</a></li>
                <li><a href="/login" class="nav-link px-2 link-dark">Peminjaman barang</a></li>
        
            <div class="col-md-3 text-end">
                <div class="dropdown">
                    <a href="/login">
                        <button class="btn btn-primary" type="button">
                            Login
                        </button>
                    </a>
                </div>
            </div>
        </header>
    </div>
    
    <div class="b-example-divider"></div>
        
    <div class="container">
        <div class="p-5 mb-4 rounded-3 img-box">
            <div class="container-fluid py-5">
                <div class="row">
                    <div class="col-md-6">
                        <h1>Data Kerjasama Perusahaan</h1>
                    </div>
                  
                </div>
            </div>
        </div>
    </div> 
    
    <div class="container">
        <h2>Data Perusahaan</h2>
    </div>

    <div class="container">
        <table id="tabelpt" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nama Perusahaan</th>
                    <th>Email Perusahaan</th>
                    <th>Keterangan</th>
                </tr>
            </thead>
         
        </table>
    </div>

    <footer id="footer" class="section-bg">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="footer-info">
                                    <h3>Visi</h3>
                                    <p>Terwuiudnya LPP TVRI yang mandiri dan Profesional guna menguatkan persatuan dan kesatuan bangsa dalam mendukung Visi dan Misi Presiden dan Wakil Presiden Yaitu lndonesia Maju yang Berdaulat, Mandiri, dan Berkepribadian Berlandaskan Gotong-royong .</p>
                                </div>
                                <div class="footer-newsletter">
                                    <h3>Misi</h3>
                                    <p>1. Memberikan dukungan teknis penyiaran publik dalam pengambilan kebijakan penyelangaraan pemerintahan / negara
                                        <br>
                                        2. Meningkatkan kualitas sumber daya manusia, sarana, dan prasarana LPP TVRI
                                        <br>
                                        3. Menyelenggarakan pelayanan yang efektif dan efisien di bidang pengelolaan sumber-sumber, pengawasan, administrasi umum, informasi dan hubungan kelembagaan</p>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="footer-links">
                                    <h4>Links</h4>
                                    <ul>
                                        <li><a href="#data_perusahaan">Data Perushaan</a></li>
                                        <li><a href="#data_inventaris_barang">Data Inventaris Barang</a></li>
                                        <li><a href="#">Basmi Hoax</a></li>
                                        <li><a href="#">Tentang TVRI</a></li>
                                    </ul>
                                </div>
                                <div class="footer-links">
                                    <h4>Hubungi Kami</h4>
                                    <p>
                                    Jl. Mayjen Sungkono No.124, Pakis, Kec. Sawahan, Kota SBY, Jawa Timur 60189 <br>
                                    <strong>Phone:</strong> (031) 5678515<br>
                                    <strong>Email:</strong> sekretariattvrijatim@gmail.com<br>
                                    </p>
                                </div>
                                <div class="social-links">
                                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15830.265211304128!2d112.69690803955078!3d-7.290083499999991!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd7fc734b7f3bd1%3A0xb549bdffa17f9ac3!2sTVRI%20Stasiun%20Jawa%20Timur!5e0!3m2!1sid!2sid!4v1661325501948!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>    
                        </div>    
                    </div>
                </div>
            </div>

           
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );    
    </script>
    <script>
        $('#example').dataTable( {
            "columnDefs": [
                { "width": "14%", "targets": 0 }
            ]
        } );
    </script>


<!-- SCRIPT AJAX -->

   


<script type="text/javascript">

  $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        });



    $(document).ready(function() {

       var table = $('#tabelpt').DataTable({
            "pageLength": 50,
           processing : true,
           serverSide : true,
           ajax: {

            url: "{{route('dataperusahaan.index')}}",
            type: 'GET',
            
             },
             columns: [{
                        data:'nama_perusahaan',
                        name:'nama_perusahaan'
                    },
                    
                    {
                        data:'email',
                        name:'email'
                    },
                    {
                        data:'keterangan',
                        name:'keterangan'
                    },

                     
                  
                ],

                order:[
                [0,'desc']
                ]


            });
//function auto reload table
            setInterval( function () {
    table.ajax.reload();
}, 3000 );
    });






</script>








</body>


</html>

resources/views/daftar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>
<body style="background-color: #152d6b; ;">
    <div class="container" style="text-align: center;">
        <div class="card-box col-md-4">
            <form action="/daftar" method="POST">
                @csrf
                <img src="img/tvri.png" alt="logo" class="img-login" >
                <!-- Name input -->
                <div class="form-outline mb-2 text-start">
                    <label class="form-label" for="name">Nama</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}"/>
                    @error('name')
                        <span class="invalid-feedback text-end" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <!-- Email input -->
                <div class="form-outline mb-2 text-start">
                    <label class="form-label" for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"/>
                    @error('email')
                        <span class="invalid-feedback text-end" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <!-- Password input -->
                <div class="form-outline mb-2 text-start">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" name="password" id="password" class="form-control @error('password') is-invalid @enderror"/>
                    @error('password')
                        <span class="invalid-feedback text-end" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-outline mb-4 text-start">
                    <label class="form-label" for="password_confirmation">Konfirmasi Password:</label>
                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" />
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-2 w-100">Daftar</button>
                <a href="/login" type="button" class="btn btn-outline-primary btn-block mb-4 w-100">Kembali</a>
            </form>
            <div class="daftar-akun mb-4">
                <p>Sudah memiliki akun? <a href="/login">Masuk</a> </p> 
            </div>
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.js" integrity="sha256-siqh9650JHbYFKyZeTEAhq+3jvkFCG8Iz+MHdr9eKrw=" crossorigin="anonymous"></script>
</body>
</html>

resources/views/email-success.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>
<body style="background-color: #152d6b; ;">
    <div class="container" style="text-align: center;">
        <div class="card-box col-md-5">
            <h4 style="color: black;" class="mb-5 mt-4">Reset Password</h4> 
 
            <div class="row col-md-8"  style="margin: auto;">
                <p>Email verifikasi telah dikirimkan ke</p>
                @if( auth()->check() )
                    <p>{{ auth()->user()->email }}</p>
                @endif
                <a href="/login" type="button" class="btn btn-outline-primary btn-block mb-4">OK</a>
            </div>
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.js" integrity="sha256-siqh9650JHbYFKyZeTEAhq+3jvkFCG8Iz+MHdr9eKrw=" crossorigin="anonymous"></script>
</body>
</html>

resources/views/email.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>
<body style="background-color: #152d6b;">
    <div class="container" style="text-align: center;">
        <div class="card-box col-md-5">
            <h4 style="color: black;" class="mb-5 mt-4">Reset Password</h4>            
            <form method="POST" action="/forget-password">
                @csrf
                <div class="form-outline mb-4 col-md-8" style="margin: auto;">
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" placeholder="Masukkan Email Anda" autocomplete="email" autofocus>

                    @error('email')
                        <span class="invalid-feedback text-start" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="row col-md-8"  style="margin: auto;">
                    <button type="submit" class="btn btn-primary mb-2">Berikutnya</button>
                    <a href="/beranda" type="button" class="btn btn-outline-primary btn-block mb-4">Kembali</a>
                </div>
            </form>
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.js" integrity="sha256-siqh9650JHbYFKyZeTEAhq+3jvkFCG8Iz+MHdr9eKrw=" crossorigin="anonymous"></script>
</body>
</html>